# Generated by Django 3.0.5 on 2020-06-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationfiles',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
        migrations.AddField(
            model_name='publicationfiles',
            name='redactor',
            field=models.BooleanField(default=False, verbose_name='Редактор'),
        ),
    ]
