# Generated by Django 3.0.5 on 2020-07-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_auto_20200709_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='description_kz',
            new_name='description_kk',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='name_kz',
            new_name='name_kk',
        ),
    ]
