# Generated by Django 3.0.5 on 2020-09-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0007_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationfiles',
            name='antiplagiat',
            field=models.BooleanField(default=False, verbose_name='Антиплагиат'),
        ),
        migrations.AddField(
            model_name='publicationfiles',
            name='payload',
            field=models.BooleanField(default=False, verbose_name='Оплата'),
        ),
        migrations.AddField(
            model_name='publicationfiles',
            name='retzenzent',
            field=models.BooleanField(default=False, verbose_name='Рецензент'),
        ),
    ]
