# Generated by Django 3.0.5 on 2020-09-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0008_auto_20200912_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationfiles',
            name='antiplagiat',
            field=models.BooleanField(blank=True, null=True, verbose_name='Антиплагиат'),
        ),
        migrations.AlterField(
            model_name='publicationfiles',
            name='payload',
            field=models.BooleanField(blank=True, null=True, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='publicationfiles',
            name='redactor',
            field=models.BooleanField(blank=True, null=True, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='publicationfiles',
            name='retzenzent',
            field=models.BooleanField(blank=True, null=True, verbose_name='Рецензент'),
        ),
    ]
