# Generated by Django 3.0.5 on 2020-09-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0011_auto_20200913_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationfiles',
            name='antiplagiat_file',
            field=models.FileField(blank=True, null=True, upload_to='antiplagiat_files', verbose_name='Файл антиплагиата'),
        ),
        migrations.AddField(
            model_name='publicationfiles',
            name='antiplagiat_point',
            field=models.IntegerField(blank=True, null=True, verbose_name='Баллы антиплагиата'),
        ),
        migrations.AddField(
            model_name='publicationfiles',
            name='retzenzent_file',
            field=models.FileField(blank=True, null=True, upload_to='antiplagiat_files', verbose_name='Файл рецензента'),
        ),
    ]
