# Generated by Django 3.0.5 on 2020-09-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0012_auto_20200913_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationfiles',
            name='retzenzent_file',
            field=models.FileField(blank=True, null=True, upload_to='review_files', verbose_name='Файл рецензента'),
        ),
    ]
