# Generated by Django 3.0.5 on 2020-09-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0014_auto_20200914_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationfiles',
            name='antiplagiat_update_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publicationfiles',
            name='redactor_update_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publicationfiles',
            name='retzenzent_update_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
