# Generated by Django 3.0.5 on 2020-09-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0022_auto_20200922_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationfiles',
            name='antiplagiat_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicationfiles',
            name='redactor_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicationfiles',
            name='reviewer_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
