# Generated by Django 3.0.5 on 2020-09-23 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0024_auto_20200922_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationfiles',
            name='payload_img',
            field=models.FileField(blank=True, null=True, upload_to='payload_img', verbose_name='Фото оплаты'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
