# Generated by Django 3.0.5 on 2020-11-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0025_auto_20200924_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationfiles',
            name='payload_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
