# Generated by Django 3.0.5 on 2020-11-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0026_publicationfiles_payload_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vestnikfiles',
            name='series',
        ),
        migrations.AddField(
            model_name='vestnikfiles',
            name='month',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12)], default=1, max_length=4, verbose_name='Месяц вестника'),
        ),
        migrations.AddField(
            model_name='vestnikfiles',
            name='number',
            field=models.CharField(default='Филологический вестник', max_length=100, verbose_name='Номер вестника'),
        ),
    ]
