# Generated by Django 3.0.5 on 2020-11-11 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0028_auto_20201112_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationfiles',
            name='series',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
