# Generated by Django 3.0.5 on 2020-11-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0046_auto_20201113_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicationfiles',
            old_name='vestnik',
            new_name='vestniks',
        ),
    ]
