# Generated by Django 3.0.5 on 2020-11-12 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0047_auto_20201113_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationfiles',
            name='vestniks',
        ),
        migrations.AddField(
            model_name='publicationfiles',
            name='vestnik',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='publication.VestnikFiles', verbose_name='Относится к вестнику'),
        ),
    ]
