# Generated by Django 3.0.5 on 2020-11-12 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0049_remove_publicationfiles_vestnik'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationfiles',
            name='vestnik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publication.VestnikFiles', verbose_name='Относится к вестнику'),
        ),
    ]
