# Generated by Django 3.0.5 on 2020-11-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0052_profile_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationfiles',
            name='payload_error',
            field=models.BooleanField(default=False, verbose_name='Оплата(Ошибка)'),
        ),
        migrations.AddField(
            model_name='publicationfiles',
            name='payload_error_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст ошибки'),
        ),
    ]
