# Generated by Django 3.1.4 on 2020-12-27 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0054_auto_20201228_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='submenu',
        ),
        migrations.AddField(
            model_name='pages',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='publication.pages'),
        ),
    ]
