# Generated by Django 3.1.4 on 2020-12-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0055_auto_20201228_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='work',
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='postCode',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='workPlace',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
